config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :journals do
    get :avatar, on: :member
    get :exhibit, on: :member
  end
  resources :notes
  resources :attachments
  get  '/upload/grid/image/:model/:mounted_as/:id/:filename' => 'gridfs#serve'

  get  '/upload/grid/file/:model/:mounted_as/:id/:filename' => 'gridfs#serve'

  get 'sessions/new'

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'

end

app/models/attachment.rb
require_relative 'validators.rb'

class Attachment
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :journal

  field :name, type: String
  field :fyle, type: String
  field :fyle_type, type: Integer, default: nil

  validates_presence_of :name
  validates_with VldBinaryTypesRange, binary_types_key: :fyle_type

  mount_uploader :fyle, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:show]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        set_mount_type(@attachment, :fyle)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        set_mount_type(@attachment, :fyle, params["attachment"])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:name, :fyle, :remove_fyle, :fyle_acache, :fyle_type)
    end
end

app/views/attachments/_form.html.slim
= bootstrap_form_for @attachment, html: {multipart: true} do |f|
  - if @attachment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@attachment.errors.count, "error")} prohibited this attachment from being saved:"
      ul
        - @attachment.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :name
  .field
    .form-group
      label.control-label for="attachment_fyle" File
      - if @attachment.fyle.blank?
        br
        | (No file set)
      - else
        br
        = binary_file_view(@attachment, :fyle)
      input#attachment_fyle name="attachment[fyle]" type="file"
  - if !@attachment.fyle.blank?
    .field
      = f.check_box :remove_fyle
  br
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/attachments/edit.html.slim
h1 Editing attachment

== render 'form'

= link_to 'Show', @attachment
'|
= link_to 'Back', attachments_path

app/views/attachments/index.html.slim
- if !@attachments.empty?
  h1 Listing attachments

  table.list-model
    thead
      tr
        th ID
        th Name
        th File
        th Type
        th
        th

    tbody
      - @attachments.each do |a|
        tr
          td.mono
            = a.id.to_s
          td = link_to a.name, a
          td
            - if a.fyle.blank?
              | N/A
            - elsif content_rmatch a.fyle.file.content_type, :image
              / We'd like to have a real thumbnail displayed, but the way
              / carrierwave works now, we cannot easily do this, as there is no
              / mechanism to check the file content type from the
              / CarrierWave::Uploader::Base class. Thus, as we cannot process
              / thumbnails for attachments (which use the FileUploader, which is
              / designed to be a generic file uploader), we display the full
              / image here, but for UI purposes, limit it to 50x50.
              = image_tag a.fyle_url, size: "50x50"
            - else
              = binary_file_view(a, :fyle)
          td
            - if a.fyle_type.nil?
              | N/A
            - else
              = BINARY_TYPES_HASH[a.fyle_type]
          td = link_to 'Edit', edit_attachment_path(a)
          td = link_to 'Destroy', a, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

= link_to 'New Attachment', new_attachment_path

app/views/attachments/new.html.slim
h1 New attachment

== render 'form'

= link_to 'Back', attachments_path

app/views/attachments/show.html.slim
p
  strong Name:&nbsp;
  = @attachment.name
p
  strong File:&nbsp;
  - if @attachment.fyle.file.nil?
    | N/A
  - else
    = binary_file_view(@attachment, :fyle)
p
  strong Type:&nbsp;
  - if @attachment.fyle_type.nil?
    | N/A
  - else
    = BINARY_TYPES_HASH[@attachment.fyle_type]

= link_to 'Edit', edit_attachment_path(@attachment)
'|
= link_to 'Back', attachments_path