config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :journals do
    get :avatar, on: :member
    get :exhibit, on: :member
  end
  resources :notes
  resources :attachments
  get  '/upload/grid/image/:model/:mounted_as/:id/:filename' => 'gridfs#serve'

  get  '/upload/grid/file/:model/:mounted_as/:id/:filename' => 'gridfs#serve'

  get 'sessions/new'

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'

end

app/models/journal.rb
require_relative 'validators.rb'
require_relative '../../lib/natree_parser.rb'

#class NaTree
#  attr_accessor :render_chain

#  @oid_chain_hash

#  def initialize()
#  end
#end

class Journal
  include Mongoid::Document
  include Mongoid::Timestamps
  include JournalHelper

  belongs_to :user
  has_many :notes
  has_many :attachments

  field :name, type: String
  field :avatar, type: String
  field :avatar_type, type: Integer, default: nil
  # textual representation of notes/attachments graph; we have to generate the
  # natree and other things at runtime
  field :natree, type: String
  # contain the actual rendered contents, so that we don't re-generate the
  # finished document every time; for now, this is raw HTML code!
  field :rendered, type: String
  field :published, type: Boolean, default: false
  field :priority, type: Integer, default: 0

  validates_presence_of :name
  validates_length_of :name, maximum: 80
  validates_with VldBinaryTypesRange, binary_types_key: :avatar_type

  mount_uploader :avatar, ImageUploader

  before_validation :standardize_strings

  private

    def standardize_strings
      # remove trailing whitespace
      self.natree.strip!
      # unixify newlines
      self.natree.gsub!("\r", "")
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  # We need to include the TextHelper class because we can use the
  # 'simple_helper' method from within 'JournalHelper'...?
  include ActionView::Helpers::TextHelper
  include JournalHelper

  before_action :set_journal, only: [:show, :edit, :update, :destroy, :exhibit]
  before_action :logged_in_user, except: [:exhibit]

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/1/exhibit
  def exhibit
    @render = gen_render(@journal.natree)
  end

  # GET /journals/new
  def new
    @journal = Journal.new\
      published: true
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params.merge!\
      user_id: current_user.id
    )

    respond_to do |format|
      if @journal.save
        set_mount_type(@journal, :avatar)
        format.html { redirect_to @journal,\
          notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors,\
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        set_mount_type(@journal, :avatar, params["journal"])
        format.html { redirect_to @journal,\
          notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors,\
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url,\
        notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def journal_params
      params.require(:journal).permit(\
        :name,\
        :user_id,\
        :avatar, :remove_avatar, :avatar_cache, :avatar_type,\
        :natree,\
        # we don't include 'rendered', because that parameter is READ-only from the DB
        :published,\
        :priority)
    end
end

app/helpers/journal_helper.rb
module JournalHelper
  # Use the '#natree' string to generate a properly-structured HTML-rendered
  # output to store into the database. We could store the AST-like structure
  # of '#natree' in JSON's string representation form, but that involves extra
  # dependencies and overhead that we do not need now.
  def gen_render(natree)
    parsed_hash = parse_natree(natree)
    phash = NatreeParserTransform.new.apply(parsed_hash)
    render_text = []

    na_chains = phash[:na_chains]
    rchain = phash[:render_chain]

    rchain.each do |chain_name|
      if na_chains.map{|nc| nc[:name]}.include?(chain_name)
        oids = get_oids(chain_name, na_chains)
        render_text << render_oids(oids)
      else
        render_text << "key #{chain_name} not found in `na_chains'\n"
      end
    end

    # Rendered output string
    render_text.join("<hr class=\"thick tallmargin\">")
  end

  def get_oids(chain_name, na_chains)
    na_chains.find {|chain| chain[:name] == chain_name}[:oids]
  end

  def render_oids(oids)
    output = []
    oids.each do |obj_type, oid|
      if obj_type == "n"
        str0 = Note.find(oid).text
        output << "<div class=\"section\">#{Kramdown::Document.new(str0).to_html.html_safe}</div>\n\n"
      else
        output << "<div class=\"attachment\"><img src=\"#{Attachment.find(oid).fyle_url}\"></div>\n\n"
      end
    end

    output.join("\n\n")
  end
end

app/views/journals/_form.html.slim
= bootstrap_form_for @journal, html: {multipart: true} do |f|
  - if @journal.errors.any?
    #error_explanation
      h2 = "#{pluralize(@journal.errors.count, "error")} prohibited this journal from being saved:"
      ul
        - @journal.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :name
  .field
    .form-group
      label.control-label for="journal_avatar" Avatar
      - if @journal.avatar.blank?
        br
        | (No avatar set)
      - else
        br
        = image_tag @journal.avatar_url(:thumb)
      input#journal_avatar name="journal[avatar]" type="file"
  - if !@journal.avatar.blank?
    .field
      = f.check_box :remove_avatar
  .field
    = f.text_area :natree, cols: 80, rows: 20
  .field
    = f.number_field :priority
  .field
    = f.label :published
    br
    = f.check_box :published
  br
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/journals/edit.html.slim
h1 Editing journal

== render 'form'

= link_to 'Show', @journal
'|
= link_to 'Back', journals_path

app/views/journals/exhibit.html.slim
.journal-name
  h1
    = @journal.name
.mini-nav
  span.fa-stack.fa-lg
    = icon('circle', '', class: 'fa-stack-2x')
    = link_to root_url, :'data-toggle' => 'tooltip', :'title' => 'Back'
      = icon('arrow-left', '', class: 'fa-stack-1x inverse')
#typeset
  = raw(@render)

app/views/journals/index.html.slim
- if !@journals.empty?
  h1 Listing journals

  table.list-model
    thead
      tr
        th Name
        th Avatar
        th Avatar Filetype
        th Priority
        th Published
        th
        th

    tbody
      - @journals.each do |j|
        tr
          td = link_to j.name, j
          td
            - if j.avatar.blank?
              | N/A
            - else
              - if j.avatar.file.content_type == "image/svg+xml"
                = image_tag j.avatar_url
              - else
                = image_tag j.avatar_url(:thumb)
          td
            - if j.avatar_type.nil?
              | N/A
            - else
              = BINARY_TYPES_HASH[j.avatar_type]
          td = nil_na(j.priority)
          td = j.published ? "Y" : "N"
          td = link_to 'Edit', edit_journal_path(j)
          td = link_to 'Destroy', j, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

= link_to 'New Journal', new_journal_path

app/views/journals/new.html.slim
h1 New journal

== render 'form'

app/views/journals/show.html.slim
p
  strong Name:&nbsp;
  = @journal.name
p
  strong Avatar:&nbsp;
  - if @journal.avatar.file.nil?
    | N/A
  - else
    = image_tag @journal.avatar_url
p
  strong Avatar Filetype:&nbsp;
  - if @journal.avatar_type.nil?
    | N/A
  - else
    = BINARY_TYPES_HASH[@journal.avatar_type]
p
  strong Natree:&nbsp;
.pf-note-text
  pre
    = @journal.natree
p
  strong Priority:&nbsp;
  = nil_na(@journal.priority)

= link_to 'Edit', edit_journal_path(@journal)
'|
= link_to 'Back', journals_path