config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :journals do
    get :avatar, on: :member
    get :exhibit, on: :member
  end
  resources :notes
  resources :attachments
  get  '/upload/grid/image/:model/:mounted_as/:id/:filename' => 'gridfs#serve'

  get  '/upload/grid/file/:model/:mounted_as/:id/:filename' => 'gridfs#serve'

  get 'sessions/new'

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'

end

app/views/layouts/_content.slim
- flash.each do |msg_type, msg|
  .alert class="alert-#{msg_type}" = msg
== yield

app/views/layouts/_footer.slim
footer.footer
  .container data-no-turbolink="true"
    p.text-muted
      - if !@ruser.email.nil?
        span.fa-stack.fa-lg
          = icon('circle', '', class: 'fa-stack-2x')
          = link_to "mailto:#{@ruser.email}", :'data-toggle' => 'tooltip', :'title' => 'Email'
            = icon('envelope', '', class: 'fa-stack-1x inverse')
      - if !@ruser.blog.nil?
        span.fa-stack.fa-lg
          = icon('circle', '', class: 'fa-stack-2x')
          = link_to "http://#{@ruser.blog}", :'data-toggle' => 'tooltip', :'title' => 'Blog'
            = icon('pencil', '', class: 'fa-stack-1x inverse')
      - if !@ruser.github.nil?
        span.fa-stack.fa-lg
          = icon('circle', '', class: 'fa-stack-2x')
          = link_to "http://github.com/#{@ruser.github}", :'data-toggle' => 'tooltip', :'title' => 'Github'
            = icon('github-alt', '', class: 'fa-stack-1x inverse')
      - if !@ruser.linkedin.nil?
        span.fa-stack.fa-lg
          = icon('circle', '', class: 'fa-stack-2x')
          = link_to "http://www.linkedin.com/in/#{@ruser.linkedin}", :'data-toggle' => 'tooltip', :'title' => 'LinkedIn'
            = icon('linkedin', '', class: 'fa-stack-1x inverse')
      span.fa-stack.fa-lg
        = icon('circle', '', class: 'fa-stack-2x')
        = link_to root_url, :'data-toggle' => 'tooltip', :'title' => 'Home'
          = icon('home', '', class: 'fa-stack-1x inverse')
      - if logged_in?
        span.fa-stack.fa-lg
          = icon('circle', '', class: 'fa-stack-2x')
          = link_to logout_path, method: :delete, :'data-toggle' => 'tooltip', :'title' => 'Logout'
            = icon('sign-out', '', class: 'fa-stack-1x inverse')
      - else
        span.fa-stack.fa-lg
          = icon('circle', '', class: 'fa-stack-2x')
          = link_to login_path, :'data-toggle' => 'tooltip', :'title' => 'Login'
            = icon('sign-in', '', class: 'fa-stack-1x inverse')

app/views/layouts/_navbar.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button [
        type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar"
        aria-expanded="false" aria-controls="navbar"
        ]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    #navbar.navbar-collapse.collapse [
        aria-expanded="false" style="height: 1px;"
      ]
      ul.nav.navbar-nav.navbar-right
        li class="#{current_page?(root_url) && 'active'}"
          = link_to "Home", root_url
        li class="#{current_page?(about_path) && 'active'}"
          = link_to "About", about_path
        li class="#{current_page?(contact_path) && 'active'}"
          = link_to "Contact", contact_path
        - if logged_in?
          li class="#{current_page?(dashboard_path) && 'active'}"
            = link_to "#{current_user.name}", dashboard_path
        li class="#{current_page?(logged_in? ? logout_path : login_path) && 'active'}"
          - if logged_in?
            = link_to "Log out", logout_path, method: :delete
          - else
            = link_to "Log in", login_path

app/views/layouts/_sidebar.slim
ul.nav.nav-sidebar
  li class="#{current_page?(journals_path) && 'active'}"
    = link_to 'Journals', journals_path
  li class="#{current_page?(notes_path) && 'active'}"
    = link_to 'Notes', notes_path
  li class="#{current_page?(attachments_path) && 'active'}"
    = link_to 'Attachments', attachments_path
  li class="#{current_page?(users_path) && 'active'}"
    = link_to 'Users', users_path

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title
      - if @journal.nil?
        = name_or_namereal
      - else
        = "#{name_or_namereal} | #{@journal.name}"
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    <link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic,700' rel='stylesheet' type='text/css'>
    = favicon_link_tag "favicon.png"
  body id="#{show_background_img_css_attr}"
    section
      .container-fluid
        .row
          - if logged_in?
            .col-sm-3.col-md-2.sidebar
              = render 'layouts/sidebar'
            .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
              = render 'layouts/content'
          - else
            = render 'layouts/content'
    = render 'layouts/footer'